project:
  type: website

website:
  title: "PS Tech"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Articles"
        href: articles/index.qmd
      - text: "News"
        href: news/index.qmd
      - text: "Podcasts"
        href: podcasts/index.qmd
      - text: "Models"
        href: models/index.qmd
      - text: "About"
        href: about.qmd

output-dir: "_site"
